/* =====================================================================
 *  snpcurate.js — SNPCurate: a registry of published maize alleles and what
 *  this release shows of each.
 *
 *  Data: window.SNP_CURATE (js/snpcurate.data.js), generated by
 *  tools/build_snpcurate.py from data/curate/snpcurate.source.json, the variant
 *  stores and their site-QC sidecars, the catalogue and the GRIN trait file.
 *  A table of the entries with filters, and a record view below it; a record
 *  opens from another tool with openCurate(id) (S.curateId). Marks: gold,
 *  outline and grey (curateBadge in data.js).
 * ===================================================================== */
(function () {

  const CU = { fText:'', fMark:'all', fStatus:'all', sortKey:null, sortDir:1, busy:null };
  const STATUS = {
    site:          {label:'Site in this release'},
    not_a_site:    {label:'Not a site',         why:'The release has no site at this position, so it cannot show the allele.'},
    not_locatable: {label:'Not locatable',      why:'The change cannot be placed on the B73 v5 gene model the release is annotated with.'},
    structural:    {label:'Structural variant', why:'The allele is a transposon or indel haplotype, which a release of SNPs and short indels cannot genotype.'},
    unreliable:    {label:'Unreliable calls',   why:'Most sites in this gene are dominated by heterozygous calls, so the release cannot genotype the allele series reliably.'},
    not_annotated: {label:'Gene not annotated', why:'The gene model is missing from the annotation behind the release’s consequence calls.'},
  };
  const MARK_NAME = {gold:'Gold', outline:'Outline', grey:'Grey'};
  const MARK_ORDER = {gold:0, outline:1, grey:2};
  // PlantCAD2: the one-pass score (release v1.4.3, 8,192-bp windows), as in the other tools; the data file keeps
  // the 512-bp pc2 too
  const SCORE_LABEL = [['pc1','PlantCAD1'],['pc2op','PlantCAD2'],['evo2','Evo2'],['esm1','ESM1'],['esm2','ESM2'],['esm3','ESM3'],['esmc','ESM-C']];
  const KIND = {causal:'Causal change', published_marker:'Published marker', tag:'Tagging site'};
  const EVIDENCE = {validated:'Validated', associated:'Associated', tag:'Tag'};

  function esc(s){ return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }
  function data(){ return (typeof window!=='undefined' && window.SNP_CURATE) || null; }
  function entries(){ return (data() && data().entries) || []; }
  function byId(id){ return entries().find(e=>e.id===id) || null; }
  function carriers(e){ return e.site ? e.site.nHet + e.site.nHom : null; }
  function fmt(v){ return v==null ? '—' : (Math.abs(v)>=100 ? Math.round(v).toLocaleString() : (+v).toFixed(2)); }
  function sc1(v){ return v==null ? '—' : (v>0?'+':'') + (+v).toFixed(1); }
  function pct(a,b){ return b ? ` (${Math.round(100*a/b)}%)` : ''; }
  function where(e){
    const c=(e.chr||'').replace('chr','chr');
    if (e.pos) return `${c}:${(+e.pos).toLocaleString()}`;
    if (e.codon_positions && e.codon_positions.length) return `${c}:${(+e.codon_positions[0]).toLocaleString()}-${(+e.codon_positions[e.codon_positions.length-1]).toLocaleString()} (codon)`;
    if (e.start) return `${c}:${(+e.start).toLocaleString()}-${(+e.end).toLocaleString()}`;
    return c;
  }
  function change(e){ return e.site && e.site.sub ? `${e.label}` : e.label; }
  function prioPill(p){ return p ? `<span class="prio ${p.toLowerCase()}">${p}</span>` : '<span class="muted">—</span>'; }

  /* ---------- filters + sort ---------- */
  function visible(){
    const q = CU.fText.trim().toLowerCase();
    let L = entries().filter(e =>
      (!q || (e.trait+' '+e.symbol+' '+e.gene).toLowerCase().includes(q)) &&
      (CU.fMark==='all' || e.mark===CU.fMark) &&
      (CU.fStatus==='all' || e.status===CU.fStatus));
    // default order: by mark (gold, outline, grey), then gene name; a header click sorts by gene or carriers
    if (!CU.sortKey) L = L.slice().sort((a,b)=>(MARK_ORDER[a.mark]-MARK_ORDER[b.mark]) || String(a.symbol).localeCompare(String(b.symbol)) || a.id.localeCompare(b.id));
    if (CU.sortKey==='gene') L = L.slice().sort((a,b)=>CU.sortDir*String(a.symbol).localeCompare(String(b.symbol)) || a.id.localeCompare(b.id));
    if (CU.sortKey==='carriers') L = L.slice().sort((a,b)=>{ const x=carriers(a), y=carriers(b);
      if (x==null && y==null) return a.id.localeCompare(b.id); if (x==null) return 1; if (y==null) return -1; return CU.sortDir*(x-y); });
    return L;
  }

  /* ---------- page ---------- */
  function render(page){
    page = page || document.getElementById('page');
    injectCSS();
    page.className = 'page fade';
    const D = data();
    if (!D){
      page.innerHTML = head() + `<div class="empty-state"><div class="ei">${ICONS.check||''}</div><h3>No curated alleles loaded</h3>
        <p>SNPCurate reads <span class="c-mono">js/snpcurate.data.js</span>, built by <span class="c-mono">make curate</span>.</p></div>`;
      return;
    }
    const counts = {gold:0, outline:0, grey:0}; entries().forEach(e=>{ counts[e.mark]=(counts[e.mark]||0)+1; });
    const stat = Object.keys(STATUS).filter(k=>entries().some(e=>e.status===k));
    page.innerHTML = head() + `
      <div class="card pad cur-legend" id="curLegend">
        ${['gold','outline','grey'].map(m=>`<div class="cur-lg">${curateBadge({id:'', mark:m, symbol:'', label:''}).replace(/onclick="[^"]*"/,'onclick="return false;"').replace(/ data-curate="[^"]*"/,'')}
          <span><b>${MARK_NAME[m]}</b> · ${esc(D.marks[m])} <span class="muted">(${counts[m]||0})</span></span></div>`).join('')}
      </div>
      <div class="filterbar cur-filters">
        <div class="fld"><label for="curText">Trait or gene</label>
          <input id="curText" type="search" value="${esc(CU.fText)}" placeholder="e.g. kernel color, su1" oninput="CURATE.setFilter('fText', this.value)"></div>
        <div class="fld"><label for="curMark">Mark</label>
          <select id="curMark" onchange="CURATE.setFilter('fMark', this.value)">
            <option value="all">All marks</option>${['gold','outline','grey'].map(m=>`<option value="${m}" ${CU.fMark===m?'selected':''}>${MARK_NAME[m]}</option>`).join('')}</select></div>
        <div class="fld"><label for="curStatus">Status in this release</label>
          <select id="curStatus" onchange="CURATE.setFilter('fStatus', this.value)">
            <option value="all">Any status</option>${stat.map(k=>`<option value="${k}" ${CU.fStatus===k?'selected':''}>${esc(STATUS[k].label)}</option>`).join('')}</select></div>
      </div>
      <div id="curTable">${tableHTML()}</div>
      <div id="curRecord">${S.curateId ? recordHTML(byId(S.curateId)) : ''}</div>`;
    if (typeof attachTT==='function') attachTT();
    if (S.curateId){ const r=document.getElementById('curRecord'); if (r && r.scrollIntoView) r.scrollIntoView({block:'start'}); }
  }
  function head(){
    return `<div class="sec"><div class="bar"></div><div>
      <div class="n">PUBLISHED ALLELES · ${esc((data()||{}).release||'')}</div>
      <h2>Curated alleles and what this release shows of them</h2>
      <p>Published maize alleles with their carriers, Site QC class, scores and trait means in this release.
      An allele the release cannot genotype is listed with the reason. Click a row for its record.</p>
    </div></div>`;
  }
  function th(label, key, tt){
    if (!key) return `<th data-tt="${esc(tt)}">${label}</th>`;
    const on = CU.sortKey===key, arrow = on ? (CU.sortDir>0?' ▲':' ▼') : ' ⇅';
    return `<th class="sortable ${on?'on':''}" data-tt="${esc(tt)}" onclick="CURATE.sort('${key}')">${label}<span class="arr">${arrow}</span></th>`;
  }
  function tableHTML(){
    const L = visible();
    if (!L.length) return `<div class="card pad muted">No curated allele matches these filters.</div>`;
    const rows = L.map(e=>{ const s=e.site, open=S.curateId===e.id;
      return `<tr class="imp-row ${open?'open':''}" data-id="${esc(e.id)}" onclick="CURATE.open('${esc(e.id)}')">
        <td style="padding-left:11px">${curateBadge(e)}</td>
        <td><b>${esc(e.symbol)}</b><div class="c-mono cur-sub">${esc(e.gene)}</div></td>
        <td>${esc(change(e))}</td>
        <td>${esc(e.trait)}</td>
        <td>${esc(STATUS[e.status] ? STATUS[e.status].label : e.status)}</td>
        <td class="num">${s ? `${s.nHet.toLocaleString()} / <b>${s.nHom.toLocaleString()}</b>` : '<span class="muted">—</span>'}</td>
        <td>${s ? siteQcPill(s.qc, s.nHet, s.nHom) : ''}</td>
        <td>${s ? prioPill(s.priority) : '<span class="muted">—</span>'}</td>
        <td class="cur-ref">${e.refs && e.refs[0] ? esc(e.refs[0].cite.replace(/\.\s.*$/,'').replace(/, et al/,' et al')) + (e.refs.length>1?` <span class="muted">+${e.refs.length-1}</span>`:'') : ''}</td>
      </tr>`; }).join('');
    return `<div class="tbl-wrap" style="max-height:none"><table class="vcf imp cur-table">
      <thead><tr>${th('Mark','', 'Gold: validated causal change, genotyped here. Outline: published marker, associated change or tag, genotyped here. Grey: known allele this release cannot show.')}
        ${th('Gene','gene','Gene symbol and B73 v5 model. Click to sort.')}${th('Change','','The published change.')}${th('Trait','','The trait the allele affects.')}
        ${th('Status in this release','','Whether the release genotypes the allele, and why not when it does not.')}
        ${th('Carriers (het / hom)','carriers','Heterozygous / homozygous carriers among the release lines. Click to sort.')}
        ${th('Site QC','','The class of the site from its heterozygous and homozygous carriers.')}${th('Priority','','The SNPMaize priority of the change, as SNPImpact computes it.')}${th('Reference','','The first publication; the record lists all.')}</tr></thead>
      <tbody>${rows}</tbody></table></div>
      <div class="pager"><div class="info">Showing <span class="mono">${L.length}</span> of <span class="mono">${entries().length}</span> curated alleles</div></div>`;
  }

  /* ---------- record ---------- */
  function recordHTML(e){
    if (!e) return '';
    const s = e.site;
    const refs = (e.refs||[]).map(r=>`<li>${esc(r.cite)}${r.doi?` · <a href="https://doi.org/${esc(r.doi)}" target="_blank" rel="noopener">doi:${esc(r.doi)}</a>`:''}</li>`).join('');
    const review = e.needs_review ? `<div class="cur-review" role="note"><b>To confirm:</b> ${esc(e.needs_review)}</div>` : '';
    const tag = e.tagged_by && byId(e.tagged_by) ? `<p>The haplotype is tagged by ${curateBadge(byId(e.tagged_by))} <a href="#" onclick="CURATE.open('${esc(e.tagged_by)}');return false;">${esc(e.tagged_by)}, ${esc(byId(e.tagged_by).label)}</a>.</p>` : '';
    const top = `<div class="cur-rh">
        <div>${curateBadge(e)} <b class="cur-sym">${esc(e.symbol)}</b> <span class="cur-lbl">${esc(e.label)}</span>
          <div class="muted cur-sub">${esc(e.id)} · <a class="c-mono" href="${maizegdbGeneURL(e.gene)}" target="_blank" rel="noopener">${esc(e.gene)}</a>
          · ${esc(KIND[e.kind]||e.kind)} · ${esc(EVIDENCE[e.evidence]||e.evidence)} · ${esc(e.trait)}</div></div>
        <button class="btn ghost" onclick="CURATE.close()" aria-label="Close the record">✕</button></div>`;
    if (!s){
      const st = STATUS[e.status] || {label:e.status, why:''};
      return `<div class="card pad cur-record" id="curRec_${esc(e.id)}">${top}
        <div class="cur-why"><b>${esc(st.label)}.</b> ${esc(st.why)} <span class="muted">(${esc(where(e))})</span></div>
        <p>${esc(e.note||'')}</p>${tag}${review}
        <div class="cur-k" style="margin-top:12px">References</div><ul class="cur-refs">${refs}</ul></div>`;
    }
    const gene = s.gene!==e.gene ? ` in <span class="c-mono" style="text-transform:none">${esc(s.gene)}</span>` : '';
    const scores = SCORE_LABEL.map(([k,l])=>`<div class="cur-score"><span>${l}</span><b class="mono">${sc1(s.scores[k])}</b>${s.rank&&s.rank[k]?`<span class="muted">rank ${s.rank[k][0]} of ${s.rank[k][1]}</span>`:''}</div>`).join('');
    const subs = s.subpop.filter(x=>x.hom).map(x=>`<tr><td>${esc(x.name)}</td><td class="num">${x.hom.toLocaleString()} of ${x.total.toLocaleString()}${pct(x.hom,x.total)}</td></tr>`).join('');
    const ctys = s.country.map((x,i)=>`<tr${i>=12?' class="cur-more" hidden':''}><td>${esc(x.name)}</td><td class="num">${x.carriers.toLocaleString()} of ${x.total.toLocaleString()}${pct(x.carriers,x.total)}</td></tr>`).join('');
    return `<div class="card pad cur-record" id="curRec_${esc(e.id)}">${top}
      <div class="cur-actions">
        <button class="btn" onclick="CURATE.toVersity('${esc(e.id)}')" ${carriers(e)?'':'disabled'}>${ICONS.dna||''} Carriers in SNPVersity</button>
        <button class="btn" onclick="CURATE.toFunction('${esc(e.id)}')">${ICONS.func||''} Gene in SNPFunction</button>
        <button class="btn" onclick="CURATE.toMap('${esc(e.id)}')">${ICONS.map||''} On the map</button>
        <span class="muted" id="curBusy">${CU.busy===e.id?'Querying all lines…':''}</span>
      </div>
      <div class="cur-grid cur-facts">
        <div><div class="cur-k">Site</div><div class="cur-v mono">${esc(e.chr)}:${(+e.pos).toLocaleString()} ${esc(e.ref.length>12?e.ref.slice(0,12)+'…':e.ref)}&gt;${esc(e.alt.length>12?e.alt.slice(0,12)+'…':e.alt)}</div></div>
        <div><div class="cur-k">Consequence${gene}</div><div class="cur-v"><span class="cons ${esc(s.consClass)}">${esc(s.consequence)}</span>${s.sub?` <span class="c-mono">${esc(s.sub)}</span>`:''} <span class="muted">${esc(s.impact)}</span></div></div>
        <div><div class="cur-k">Site QC</div><div class="cur-v">${siteQcPill(s.qc, s.nHet, s.nHom)} ${s.nHet.toLocaleString()} het · ${s.nHom.toLocaleString()} hom · ${s.nMiss.toLocaleString()} missing</div></div>
        <div><div class="cur-k">Allele frequency</div><div class="cur-v">${s.af==null?'—':(s.af*100).toFixed(1)+'%'} <span class="muted">among called lines · MAF ${s.maf==null?'—':s.maf} · max LD r² ${s.maxr2==null?'—':s.maxr2}</span></div></div>
        <div><div class="cur-k">Priority</div><div class="cur-v">${prioPill(s.priority)} <span class="muted">combined ${s.combined==null?'—':(s.combined>0?'+':'')+(+s.combined).toFixed(2)}</span></div></div>
      </div>
      <div class="cur-k" style="margin-top:14px">Scores${s.rank?` <span class="muted" style="text-transform:none;font-weight:400">· rank among the ${s.rankPool} missense variants of the gene that have a carrier (1 = most negative)</span>`:''}</div>
      <div class="cur-scores">${scores}</div>
      ${s.trait ? traitHTML(s.trait) : ''}
      <div class="cur-two">
        <div><div class="cur-k">Homozygous carriers by subpopulation</div>
          <table class="cur-mini"><tbody>${subs || '<tr><td class="muted">No homozygous carrier</td></tr>'}</tbody></table></div>
        <div><div class="cur-k">Carriers by country of origin</div>
          <table class="cur-mini"><tbody>${ctys}</tbody></table>
          ${s.country.length>12?`<button class="link-btn" onclick="this.previousElementSibling.querySelectorAll('.cur-more').forEach(r=>r.hidden=false);this.remove()">Show all ${s.country.length} countries</button>`:''}</div>
      </div>
      <p style="margin-top:14px">${esc(e.note||'')}</p>${tag}${review}
      <div class="cur-k" style="margin-top:12px">References</div><ul class="cur-refs">${refs}</ul></div>`;
  }
  function traitHTML(t){
    const head = `<div class="cur-k" style="margin-top:14px">${esc(t.name)} by genotype <span class="muted" style="text-transform:none;font-weight:400">· GRIN descriptor ${t.url?`<a href="${esc(t.url)}" target="_blank" rel="noopener">${esc(t.descriptor)}</a>`:esc(t.descriptor)}</span></div>`;
    if (t.scale === 'numeric'){
      const u = t.unit ? ` ${esc(t.unit)}` : '';
      return head + `<table class="cur-mini cur-trait"><tbody>
        <tr><td>Homozygous for the alternate allele</td><td class="num"><b>${fmt(t.alt.mean)}</b>${u} <span class="muted">(n = ${t.alt.n.toLocaleString()})</span></td></tr>
        <tr><td>Homozygous for the reference allele</td><td class="num"><b>${fmt(t.ref.mean)}</b>${u} <span class="muted">(n = ${t.ref.n.toLocaleString()})</span></td></tr></tbody></table>`;
    }
    return head + `<table class="cur-mini cur-trait"><thead><tr><th>${esc(t.name)}</th><th class="num">Homozygous alternate</th></tr></thead><tbody>${(t.codes||[]).map(c=>
      `<tr><td>${esc(c.label)} <span class="muted">(${esc(c.code)})</span></td><td class="num">${c.alt.toLocaleString()} of ${c.lines.toLocaleString()}${pct(c.alt,c.lines)}</td></tr>`).join('')}</tbody></table>`;
  }

  /* ---------- hand-offs ---------- */
  function ds(){ return Data.datasets()[0].id; }
  async function interval(e){
    const g = await Data.lookupGene(e.gene);
    if (!g || !g.chr || g.chr !== e.chr) return {chr:e.chr, start:+e.pos, end:+e.pos};
    return {chr:g.chr, start:Math.min(+g.start, +e.pos), end:Math.max(+g.end, +e.pos)};
  }

  function injectCSS(){
    if (document.getElementById('snpcurate-css')) return;
    const s=document.createElement('style'); s.id='snpcurate-css';
    s.textContent=`
      .cur-grid{display:flex;gap:22px;flex-wrap:wrap}
      .cur-k{font-size:10.5px;font-weight:600;color:var(--muted);text-transform:uppercase;letter-spacing:.4px;margin-bottom:4px}
      .cur-v{font-size:14px;color:var(--ink)}
      .cur-legend{display:flex;flex-direction:column;gap:6px;margin-bottom:6px;font-size:13px}
      .cur-lg{display:flex;align-items:baseline;gap:8px}
      .cur-filters .fld input{border:1px solid var(--line);border-radius:9px;padding:8px 10px;min-width:min(240px,100%)}
      .cur-sub{font-size:11.5px;color:var(--muted)}
      .cur-ref{font-size:12px;white-space:nowrap}
      .cur-table td{vertical-align:top}
      .cur-record{margin-top:16px}
      .cur-rh{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}
      .cur-sym{font-size:17px} .cur-lbl{font-size:15px;color:var(--ink)}
      .cur-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:12px 0 14px}
      .cur-facts{row-gap:12px}
      .cur-scores{display:flex;flex-wrap:wrap;gap:8px;margin-top:6px}
      .cur-score{display:flex;flex-direction:column;gap:1px;background:#f5f8fc;border:1px solid var(--line);border-radius:9px;padding:6px 10px;min-width:92px;font-size:11.5px;color:var(--muted)}
      .cur-score b{font-size:15px;color:var(--ink)}
      .cur-two{display:flex;gap:24px;flex-wrap:wrap;margin-top:14px}
      .cur-two>div{flex:1 1 260px;min-width:0}
      .cur-mini{border-collapse:collapse;font-size:12.5px;margin-top:6px;width:100%;max-width:420px}
      .cur-mini td,.cur-mini th{padding:3px 8px 3px 0;border-bottom:1px solid #eef1f5;text-align:left}
      .cur-mini td.num,.cur-mini th.num{text-align:right}
      .cur-trait{max-width:520px}
      .cur-why{background:#f2f4f7;border:1px solid #d5dae2;border-radius:9px;padding:9px 12px;margin:12px 0;font-size:13px}
      .cur-review{background:#fff7e6;border:1px solid #f0d9a8;border-left:4px solid #c27c0e;border-radius:9px;padding:9px 12px;margin:10px 0;font-size:13px}
      .cur-refs{margin:6px 0 0 18px;padding:0;font-size:12.5px;line-height:1.6}
      .cur-refs a{word-break:break-all}`;
    document.head.appendChild(s);
  }

  window.CURATE = {
    setFilter(k, v){ CU[k]=v; const t=document.getElementById('curTable'); if (t){ t.innerHTML=tableHTML(); if (typeof attachTT==='function') attachTT(); } },
    sort(k){ if (CU.sortKey===k) CU.sortDir*=-1; else { CU.sortKey=k; CU.sortDir = k==='carriers' ? -1 : 1; }
      const t=document.getElementById('curTable'); if (t){ t.innerHTML=tableHTML(); if (typeof attachTT==='function') attachTT(); } },
    open(id){ S.curateId = (S.curateId===id ? null : id); render(); },
    close(){ S.curateId = null; render(); },
    async toVersity(id){
      const e = byId(id); if (!e || !e.site) return;
      const iv = await interval(e);
      Handoff.toVersity({from:'SNPCurate', dataset:ds(), gene:e.gene, chr:iv.chr, start:iv.start, end:iv.end,
        accessions:e.site.carriers.hom.concat(e.site.carriers.het), merge:'replace',
        note:`carriers of ${e.symbol} ${e.label} (${e.id})`});
    },
    toFunction(id){ const e=byId(id); if (!e) return; S.functionGene=e.gene; S.functionDataset=ds(); go('snpfunction'); },
    async toMap(id){
      const e = byId(id); if (!e || !e.site) return;
      CU.busy = id; const b=document.getElementById('curBusy'); if (b) b.textContent='Querying all lines…';
      try {
        const res = await Data.queryVariants(ds(), e.chr, +e.pos, +e.pos, Data.accessionsFor(ds()).map(a=>a.id));
        res.q = {dataset:ds(), chr:e.chr, lo:+e.pos, hi:+e.pos};
        S.geoInput = Object.assign(resultHandoff(res), {requeried:true});
        go('snpgeo');
      } finally { CU.busy = null; }
    },
    entries, byId,
  };

  SNPTools.register('snpcurate', { render });
})();
